### ISSUE TITLE
Import of enums causes error for webpack

### ISSUE THREAD

**Issue by thomashaenig** [senseexcel/ser-api-nuget#30]
When importing a enum it causes a error for the webpack build process. This is probably caused, because webpack should not transpile ts files in node_modules folder.

@konne  can you assist please

**Comment by konne** [comment]
@thomashaenig please try this attached file, if this solves the issue, I will change the build proess

[npm.zip](https://github.com/senseexcel/ser-api-nuget/files/2165730/npm.zip)

**Comment by thomashaenig** [comment]
@konne it is working perfect, thanks
