### ISSUE TITLE
missing //summary Docu

### ISSUE THREAD

**Issue by konne** [senseexcel/ser-api-nuget#31]
please add good long /// docu on every field / class / enum so that
1. the build process have no warnings anymore
![image](https://user-images.githubusercontent.com/1100969/42309922-529bc96c-803a-11e8-9b87-772591687bdf.png)

2. the docu is really helpfull as Docu

**Comment by mossbeard** [comment]
The Api is now documented.

**Comment by konne** [comment]
@mossbeard please make a PR to the master branch so that I can create a new release
